# Generated by Django 4.2.16 on 2024-10-20 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colourtype',
            old_name='type',
            new_name='colour_type',
        ),
    ]
