# Generated by Django 4.2.16 on 2024-10-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_type_colourtype_colour_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='colourtype',
            name='first_value',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue'), ('hue', 'hue'), ('saturation', 'saturation'), ('lightness', 'lightness')], default='red', max_length=20),
        ),
        migrations.AddField(
            model_name='colourtype',
            name='second_value',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue'), ('hue', 'hue'), ('saturation', 'saturation'), ('lightness', 'lightness')], default='green', max_length=20),
        ),
        migrations.AddField(
            model_name='colourtype',
            name='third_value',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue'), ('hue', 'hue'), ('saturation', 'saturation'), ('lightness', 'lightness')], default='blue', max_length=20),
        ),
    ]
